version: 0.2

env:
  variables:

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Region = ${AWS_REGION}"
      - echo "Account Id = $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')"
      - echo "Repo Name = ${IMAGE_REPO_NAME}"
      - echo "Commit Id = ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "Build Number = ${CODEBUILD_BUILD_NUMBER}"
      - echo "IMAGE_NAME = ${IMAGE_NAME}"
      - echo "IMAGE = $IMAGE_NAME"
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_NAME:${CODEBUILD_BUILD_NUMBER} .
      - docker tag $IMAGE_NAME:${CODEBUILD_BUILD_NUMBER} "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE}"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_IMAGE_NAME